version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME_FRONTEND:$PROJECT_NAME-$IMAGE_TAG ./Application/FrontEnd/
      - docker build -t $IMAGE_REPO_NAME_FRONTEND:$PROJECT_NAME-$IMAGE_TAG ./Application/BackEnd/
      - echo Finishing building Docker image
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME_FRONTEND:$PROJECT_NAME-$IMAGE_TAG
      - docker push $IMAGE_REPO_NAME_BACKEND:$PROJECT_NAME-$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME_FRONTEND:$PROJECT_NAME-$IMAGE_TAG  $IMAGE_REPO_NAME_FRONTEND:$PROJECT_NAME-latest 
      - docker tag $IMAGE_REPO_NAME_BACKEND:$PROJECT_NAME-$IMAGE_TAG $IMAGE_REPO_NAME_BACKEND:$PROJECT_NAME-latest  
      - docker push $IMAGE_REPO_NAME_FRONTEND:$PROJECT_NAME-latest   
      - docker push $IMAGE_REPO_NAME_BACKEND:$PROJECT_NAME-latest  
      - echo Finishing pushing Docker image... 