---
apiVersion: v1
kind: Secret
metadata:
  name: backend-user
  namespace: application
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovLzE3Mi4yMC4xNS40MA==
  SECRET_OR_KEY: QU9nUGVURjhqNGR0TEZNa1V6SnJSZEdOOWQzNWFKWmI=
---
