apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: application
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: application.onredes.com
    http:
      paths:
      - backend:
          serviceName: frontend-user-nodeport
          servicePort: 80
---