---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip
  labels:
    app: mongodb-clusterip
spec:
  type: ClusterIP
  clusterIP: 172.20.15.40
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb-statefull
---