apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistentvolumeclaim
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 10Gi