---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-clusterip
  labels:
    app: mongodb-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    clusterIP: 10.100.168.15
  selector:
    app: mongodb-statefull
---